runtime: nodejs10
env:
  - 'MONGO_URI= $_MONGO_URI'
  - 'RECAPTCHA= $_RECAPTCHA'
  - 'VKONTAKTE_APP_ID= $_VKONTAKTE_APP_ID'
  - 'VKONTAKTE_APP_SECRET= $_VKONTAKTE_APP_SECRET'
  - 'VK_CALLBACK= $_VK_CALLBACK'
  - 'SECRET= $_SECRET'
