steps:
  - name: 'gcr.io/$PROJECT_ID/npm:latest'
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/npm:latest'
    args: ['build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']
